-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 17:08:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `idUser_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Document` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Document` (
  `DocID` INT NOT NULL,
  `AuthorID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DocID`),
  UNIQUE INDEX `DocID_UNIQUE` (`DocID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Access` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Access` (
  `AccessID` INT NOT NULL,
  `Document_DocID` INT NOT NULL,
  `User_UserID` INT NOT NULL,
  PRIMARY KEY (`AccessID`),
  INDEX `fk_Access_Document_idx` (`Document_DocID` ASC) VISIBLE,
  INDEX `fk_Access_User1_idx` (`User_UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Access_Document`
    FOREIGN KEY (`Document_DocID`)
    REFERENCES `mydb`.`Document` (`DocID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Access_User1`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paragraph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Paragraph` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Paragraph` (
  `ParID` INT NOT NULL,
  `Document_DocID` INT NOT NULL,
  PRIMARY KEY (`ParID`),
  INDEX `fk_Paragraph_Document1_idx` (`Document_DocID` ASC) VISIBLE,
  CONSTRAINT `fk_Paragraph_Document1`
    FOREIGN KEY (`Document_DocID`)
    REFERENCES `mydb`.`Document` (`DocID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `TagID` INT NOT NULL,
  `tag` JSON NOT NULL,
  PRIMARY KEY (`TagID`),
  UNIQUE INDEX `TagID_UNIQUE` (`TagID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Link` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Link` (
  `LinkID` INT NOT NULL,
  `TagIndex` VARCHAR(45) NOT NULL,
  `Paragraph_ParID` INT NOT NULL,
  `Tag_TagID` INT NOT NULL,
  PRIMARY KEY (`LinkID`, `TagIndex`),
  UNIQUE INDEX `LinkID_UNIQUE` (`LinkID` ASC) VISIBLE,
  INDEX `fk_Link_Paragraph1_idx` (`Paragraph_ParID` ASC) VISIBLE,
  INDEX `fk_Link_Tag1_idx` (`Tag_TagID` ASC) VISIBLE,
  CONSTRAINT `fk_Link_Paragraph1`
    FOREIGN KEY (`Paragraph_ParID`)
    REFERENCES `mydb`.`Paragraph` (`ParID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Link_Tag1`
    FOREIGN KEY (`Tag_TagID`)
    REFERENCES `mydb`.`Tag` (`TagID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
